[project]
name = "olist"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Musharraf-Bubere", email = "musharrafbubere007@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
    "seaborn>=0.13.2",
]

[project.scripts]
olist = "olist:main"

[build-system]
requires = ["uv_build>=0.10.4,<0.11.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.4.0",
    "jupyter>=1.1.1",
    "pytest>=9.1.1",
    "ruff>=0.16.9",
]
